# Teaclave Runtime Config
#
# Note that this config is loaded at running time. We don't have to trust the
# content though. Maliciously crafted config from this file will not break data
# confidentiality/integrity.
#
# Topology of Services
#
#      ┌───────────────────────────────────────────────────┐
#      │                                                   │FNS API Endpoint
#      │                                                   ▼
#      │                                        ┌─────────────────────┐
#      │                                        │Function Node Service│
#      │          TMS Internal ┌────────────────│        (FNS)        │─┐
#      │            Endpoint   │                └─────────────────────┘ │
#      │                       ▼                           │            │
# ┌────────┐       ┌───────────────────────┐               │            │  ┌──────────────────────┐
# │  User  │       │Task Management Service│  ┌────────────┘            │  │Key Management Service│
# │        │──────▶│         (TMS)         │  │                         ├─▶│        (KMS)         │
# └────────┘       └───────────────────────┘  │                         │  └──────────────────────┘
#      │   TMS API Endpoint    │              │  ┌───────────────────┐  │KMS Internal
#      │                       │              │  │Trusted Distributed│  │  Endpoint
#      │                       └──────────────┴─▶│    File System    │──┘
#      │                            TDFS Internal│      (TDFS)       │
#      │                              Endpoint   └───────────────────┘
#      │                                                   ▲
#      │                                                   │ TDFS API Endpoint
#      └───────────────────────────────────────────────────┘

[audit]
enclave_info = { path = "enclave_info.toml" }
auditor_signatures = [
    { path = "auditors/godzilla/godzilla.sign.sha256" },
    { path = "auditors/optimus_prime/optimus_prime.sign.sha256" },
    { path = "auditors/albus_dumbledore/albus_dumbledore.sign.sha256" },
]
