[package]
name = "teaclave_utils"
version = "0.1.0"
authors = ["MesaTEE Authors <developers@mesatee.org>"]
description = "MesaTEE utilities."
license = "Apache-2.0"
edition = "2018"

[features]
default = ["mesalock_sgx"]
mesalock_sgx = ["sgx_tstd"]

[dependencies]
#ring         = { version = "0.16.5" }
#serde        = { version = "1.0.105" }
#serde_derive = { version = "1.0.105" }
#sgx_tstd     = { version = "1.1.0", optional = true }
#sgx_types    = { version = "1.1.0" }
#toml         = { version = "0.5.3" }

ring          = { git = "https://github.com/mesalock-linux/ring-sgx", tag = "v0.16.5" }
sgx_tstd      = { rev = "v1.1.2", git = "https://github.com/apache/teaclave-sgx-sdk.git", optional = true }
sgx_types     = { rev = "v1.1.2", git = "https://github.com/apache/teaclave-sgx-sdk.git"}
serde_derive  = { git = "https://github.com/mesalock-linux/serde-sgx" }
serde         = { git = "https://github.com/mesalock-linux/serde-sgx", features = ["derive"] }
toml          = { git = "https://github.com/mesalock-linux/toml-rs-sgx" }
