apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloc-demo 
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: helloc 
  template:
    metadata:
      labels:
        app: helloc 
    spec:
      containers:
      - name: helloc 
        image: {{your helloworld}}
        imagePullPolicy: Always
        command: /root/start.sh
        env:
        - name: IAS_KEY
          value: {{your key}}
        - name: IAS_SPID
          value: {{your spid}}
        - name: RUST_LOG
          value: debug
        resources:
          limits:
            cpu: 250m
            memory: 512Mi
            alibabacloud.com/sgx_epc_MiB: 2
        volumeMounts:
        - mountPath: /dev/sgx/enclave
          name: sgxdevice
        securityContext:
          privileged: true
      volumes:
      - hostPath:
          path: /dev/sgx/enclave
        name: sgxdevice
