apiVersion: v1
kind: Service
metadata:
  name: endorser-service
spec:
  type: NodePort
  selector:
    app: endorser
  ports:
    - protocol: TCP
      targetPort: 8082 
      port: 8082 
      nodePort: 30007
